version: '2'

services:
  db:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  lingoapp:
    depends_on:
      - 'db'
    image: test_docker
    command: >
           bash -c "python server.py &&
                    fg"
    ports:
      - '8001:8001'
    volumes:
      - '.:/app'
volumes:
  mongo:

