version: "3"

services:
  #  db:
  #    image: 'mongo:3.4.1'
  #    ports:
  #      - '27017:27017'
  #    volumes:
  #      - 'mongo:/data/db'

  lingoapp:
    build: ./webapp
    command: python main.py
    ports:
      - "8000:8000"
    volumes:
      - "./webapp:/app"
    links:
      - "review-comparer:review-comparer"
      - "sentiment-classifier:sentiment-classifier"
      - "generator:generator"
      - "transferrer:transferrer"

  review-comparer:
    build: ./lingofunk-classify-relevance
    command: bash -c "PYTHONPATH=. python -m lingofunk_classify_relevance.app.server --port 8000"
    volumes:
      - "./lingofunk-classify-relevance:/app"

  transferrer:
    build: ./lingofunk-transfer-style
    command:
      - /bin/sh
      - -c
      - |
        python \
        -m   lingofunk_transfer_style \
        --mode=serve  \
        --port=8000 \
        --load_models \
        --no_cuda
    volumes:
      - "../lingofunk-data:/app/output"

  sentiment-classifier:
    build: ./lingofunk-classify-sentiment
    command: python -m lingofunk_classify_sentiment.app.run
    volumes:
      - "./lingofunk-classify-sentiment:/app"

  generator:
    build: ./lingofunk-generate
    command: python ./lingofunk_generate/server.py
    volumes:
      - "./lingofunk-generate:/app"
#  worker_template:
#    build: ./worker_template
#    command: python main.py
#    volumes:
#      - ./worker_template:/app
