version: '3'

services:
#  db:
#    image: 'mongo:3.4.1'
#    ports:
#      - '27017:27017'
#    volumes:
#      - 'mongo:/data/db'

  lingoapp:
    build: ./webapp
    command: python main.py
    ports:
      - '8000:8000'
    volumes:
      - './webapp:/app'
    links:
      - 'worker_one:worker_one'

  worker_one:
    build: ./worker_one
    command: python main.py
    volumes:
      - ./worker_one:/app

