version: "3"

services:
  #  db:
  #    image: 'mongo:3.4.1'
  #    ports:
  #      - '27017:27017'
  #    volumes:
  #      - 'mongo:/data/db'

  lingoapp:
    build: ./webapp
    command: python main.py
    ports:
      - "8000:8000"
    volumes:
      - "./webapp:/app"
    links:
      - "sentiment-classifier:sentiment-classifier"
      - "generator:generator"
  #      - "worker_template:worker_template"

  review-comparer:
    build: ./lingofunk-classify-relevance
    command: python ./lingofunk_classify_relevance/server.py
    volumes:
      - "./lingofunk-classify-relevance:/app"

  sentiment-classifier:
    build: ./lingofunk-classify-sentiment
    command: python -m lingofunk_classify_sentiment.app.run
    volumes:
      - "./lingofunk-classify-sentiment:/app"

  generator:
    build: ./lingofunk-generate
    command: python ./lingofunk_generate/server.py
    volumes:
      - "./lingofunk-generate:/app"
#  worker_template:
#    build: ./worker_template
#    command: python main.py
#    volumes:
#      - ./worker_template:/app
